# -*- coding: utf-8 -*-
"""이미지 회전, 반전 코드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzHzJY7oAcnGW4mQAedanghZRCZopfoI
"""

#90, 180, 270, 좌우반전, 상하반전 코드

#opencv를 선언
import cv2
from google.colab.patches import cv2_imshow
import os
import glob
D="./train_image"


#원하는 이미지를 불러오는 코드 입력
i=0
d=520
e=1040
for f in glob.glob("./train_image/Atopic*.*"):
  i+=1
  d+=1
  e+=1
  img = cv2.imread(f,cv2.IMREAD_COLOR)
  
  img90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE) # 시계방향으로 90도 회전
  img180 = cv2.rotate(img, cv2.ROTATE_180) # 180도 회전
  img270 = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE) # 반시계방향으로 90도 회전 
                                                          # = 시계방향으로 270도 회전
  img_lr = cv2.flip(img, 1) #좌우반전
  img_ud = cv2.flip(img, 0) #상하반전

  #이미지 사이즈 맞추는 코드
  img = cv2.resize(img, dsize=(256,256),interpolation=cv2.INTER_AREA)
  img_lr = cv2.resize(img_lr, dsize=(256,256),interpolation=cv2.INTER_AREA)
  img_ud = cv2.resize(img_ud, dsize=(256,256),interpolation=cv2.INTER_AREA)

  #저장하는 코드
  cv2.imwrite('./train_img/'+ 'Atopic'+' (' + str(i) +')'+ '.jpg',img)
  cv2.imwrite('./train_img/'+ 'Atopic'+' (' + str(d) +')'+ '.jpg',img_lr)
  cv2.imwrite('./train_img/'+ 'Atopic'+' (' + str(e) +')'+ '.jpg',img_ud)

  cv2.waitKey(0)
  cv2.destroyAllWindows()

!pwd

!cat /etc/issue

cd drive/MyDrive

import os
path="./train_image"
acne=0
actinic=0
atopic=0
psoriasis=0
Seborrheic=0

for filename in os.listdir(path):

    if "Acne" in filename:
        acne+=1
    if "Actinic" in filename:
        actinic+=1
    if "Atopic" in filename:
        atopic+=1

    if "Psoriasis" in filename:
        psoriasis+=1
    if "Seborrheic" in filename:
        Seborrheic+=1


print(acne, #1713
    actinic, #764
    atopic, #700

    psoriasis,# 565
    Seborrheic)

from google.colab import drive
drive.mount('/content/drive')

cd drive/MyDrive

import shutil
filename='./test_image.zip'
extract_dir='./test_image'
archive_format="zip"
shutil.unpack_archive(filename,extract_dir,archive_format)